<?php
namespace Selenia\Plugins\MatisseComponents\Handlers;

use Psr\Http\Message\UploadedFileInterface;
use Selenia\Application;
use Selenia\Exceptions\FlashMessageException;
use Selenia\Exceptions\FlashType;
use Selenia\Interfaces\ModelControllerExtensionInterface;
use Selenia\Interfaces\ModelControllerInterface;
use Selenia\Plugins\AdminInterface\Models\File;
use Selenia\Plugins\MatisseComponents\ImageField;

class ImageFieldHandler implements ModelControllerExtensionInterface
{
  /** @var string */
  private $fileArchivePath;

  public function __construct (Application $app)
  {
    $this->fileArchivePath = $app->fileArchivePath;
  }

  /*
   * Detect if the request has fields that were generated by this component; if so, register an handler for saving
   * them.
   */
  function modelControllerExtension (ModelControllerInterface $modelController)
  {
    $request = $modelController->getRequest ();
    $files   = $request->getUploadedFiles ();
    $uploads = [];

    // Check if extension is applicable to the current request.
    foreach ($files as $fieldName => $file)
      if (str_endsWith ($fieldName, ImageField::FILE_FIELD_SUFFIX)) {
        $fieldName           = explode ('_', $fieldName) [0];
        $uploads[$fieldName] = $file;
      }

    if ($uploads)
      $modelController->onBeforeSave (function () use ($uploads, $modelController) {
        /** @var UploadedFileInterface $file */
        foreach ($uploads as $fieldName => $file) {
          $err = $file->getError ();
          if ($err == UPLOAD_ERR_OK)
            static::saveUpload ($fieldName, $file, $modelController);
          else if ($err == UPLOAD_ERR_NO_FILE)
            static::noUpload ($fieldName, $modelController);
          else throw new FlashMessageException ("Error $err", FlashType::ERROR, "Error uploading file");
        }
      });
  }

  private function deleteFile ($fileId)
  {
    $file = File::find ($fileId);
    if ($file) {
      $path = "$this->fileArchivePath/$file->path";
      if (file_exists ($path))
        unlink ($path);
      $file->delete ();
    }
  }

  private function noUpload ($fieldName, ModelControllerInterface $modelController)
  {
    /** @var File $model */
    $model      = $modelController->getModel ();
    $prevFileId = $model->getOriginal ($fieldName);
    if (!exists ($model->$fieldName) && exists ($prevFileId))
      $this->deleteFile ($prevFileId);
  }

  private function saveUpload ($fieldName, UploadedFileInterface $file, ModelControllerInterface $modelController)
  {
    $model = $modelController->getModel ();

    $filename = $file->getClientFilename ();
    $n        = explode ('.', $filename);
    $ext      = array_pop ($n);
    $name     = implode ('.', $n);
    $id       = uniqid ();
    $type     = $file->getClientMediaType ();
    $isImage  = array_search ($type, ['image/jpeg', 'image/png', 'image/gif', 'image/tiff', 'image/bmp']) !== false;

    $fileModel = $model->files ()->create ([
      'id'    => $id,
      'name'  => $name,
      'ext'   => $ext,
      'image' => $isImage,
    ]);

    $path = "$this->fileArchivePath/$fileModel->path";
    $dir  = dirname ($path);
    if (!file_exists ($dir))
      mkdir ($dir, 0777, true);
    $file->moveTo ($path);

    // Delete the previous file for this field, if one exists.
    if (exists ($model->$fieldName))
      $this->deleteFile ($model->$fieldName);

    $model->$fieldName = $id;
  }

}
