<?php

namespace Electro\Plugins\MatisseComponents\Handlers;

use Electro\ContentRepository\Config\ContentRepositorySettings;
use Electro\ContentRepository\Lib\FileUtil;
use Electro\Exceptions\FlashMessageException;
use Electro\Exceptions\FlashType;
use Electro\Interfaces\ContentRepositoryInterface;
use Electro\Interfaces\ModelControllerExtensionInterface;
use Electro\Interfaces\ModelControllerInterface;
use Electro\Plugins\MatisseComponents\ImageField;
use Electro\Plugins\MatisseComponents\Models\File;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Psr\Http\Message\UploadedFileInterface;

class ImageFieldHandler implements ModelControllerExtensionInterface
{
  /** @var string */
  private $fileArchivePath;
  /** @var ContentRepositoryInterface */
  private $repository;

  public function __construct (ContentRepositorySettings $settings, ContentRepositoryInterface $repository)
  {
    $this->fileArchivePath = $settings->fileArchivePath;
    $this->repository      = $repository;

    // Watch for file model deletions and remove the corresponding physical files.
    File::deleting (function (File $model) use ($repository) {
      if (exists ($model->path))
        $repository->deleteFile ($model->path);
    });
  }

  /*
   * Detect if the request has fields that were generated by this component; if so, register an handler for saving
   * them.
   */
  function modelControllerExtension (ModelControllerInterface $modelController)
  {
    $request = $modelController->getRequest ();
    $files   = $request->getUploadedFiles ();
    $uploads = [];

    // Check if extension is applicable to the current request.
    foreach ($files as $fieldName => $file)
      if (str_endsWith ($fieldName, ImageField::FILE_FIELD_SUFFIX)) {
        // Note: slashes are converted to dots, which delimit path segments to nested fields. See the Field component.
        $fieldName           = str_replace ('/', '.', str_segmentsStripLast ($fieldName, '_'));
        $uploads[$fieldName] = $file;
      }

    if ($uploads)
      $modelController->onSave (-1, function () use ($uploads, $modelController) {
        /** @var UploadedFileInterface $file */
        foreach ($uploads as $fieldName => $file) {
          list ($targetModel, $prop) = $modelController->getTarget ($fieldName);
          $err = $file->getError ();
          if ($err == UPLOAD_ERR_OK)
            static::newUpload ($targetModel, $prop, $file);
          else if ($err == UPLOAD_ERR_NO_FILE)
            static::noUpload ($targetModel, $prop);
          else throw new FlashMessageException ("Error $err", FlashType::ERROR, "Error uploading file");
        }
      });
  }

  /**
   * Handle the case where a file has been uploaded for a field, possibly replacing another already set on the field.
   *
   * @param Model                 $model
   * @param string                $fieldName
   * @param UploadedFileInterface $file
   * @throws \Exception
   * @throws \League\Flysystem\FileExistsException
   * @throws \League\Flysystem\InvalidArgumentException
   */
  private function newUpload (Model $model, $fieldName, UploadedFileInterface $file)
  {
    // Check is there is a previous file for this field.
    /** @var Collection $files */
    $files = $model->files;
    /** @var File $prevFile */
    $prevFile = $files->count () ? $files->first () : null;

    $data = File::getFileData ($file->getClientFilename (), FileUtil::getUploadedFilePath ($file), $fieldName);
    /** @var File $fileModel */
    $fileModel = $model->files ()->create ($data);
    $this->repository->saveUploadedFile ($fileModel->path, $file);

    // Delete the previous file for this field, if one exists. This is only performed AFTER the new file is successfully
    // uploaded.
    if ($prevFile)
      $prevFile->delete ();

    $model[$fieldName] = $fileModel->path;
    $model->save ();
  }

  /**
   * Handle the case where no file has been uploaded for a field, but the field may have been cleared.
   *
   * @param Model  $model
   * @param string $fieldName
   * @throws \Exception
   */
  private function noUpload (Model $model, $fieldName)
  {
    if (!isset($model[$fieldName])) {
      // Check is there was a file on this field.
      /** @var Collection $files */
      $files = $model->files;
      /** @var File $prevFile */
      $prevFile = $files->count () ? $files->first () : null;

      // Delete the previous file for this field, if one exists.
      if ($prevFile)
        $prevFile->delete ();
    }
  }

}
